"""empty message

Revision ID: 12778e0d070e
Revises: 834b1a697901
Create Date: 2020-06-03 13:15:59.956357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12778e0d070e'
down_revision = '834b1a697901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=128), nullable=True),
    sa.Column('lname', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('zipcode', sa.String(length=128), nullable=True),
    sa.Column('insured', sa.String(length=128), nullable=True),
    sa.Column('gender', sa.String(length=128), nullable=True),
    sa.Column('birthDate', sa.String(length=128), nullable=True),
    sa.Column('martial', sa.String(length=128), nullable=True),
    sa.Column('military', sa.String(length=128), nullable=True),
    sa.Column('homeOwner', sa.String(length=128), nullable=True),
    sa.Column('education', sa.String(length=128), nullable=True),
    sa.Column('occupation', sa.String(length=128), nullable=True),
    sa.Column('credit', sa.String(length=128), nullable=True),
    sa.Column('accidents', sa.String(length=128), nullable=True),
    sa.Column('duis', sa.String(length=128), nullable=True),
    sa.Column('suspensions', sa.String(length=128), nullable=True),
    sa.Column('parentId', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=128), nullable=True),
    sa.Column('phoneVerified', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead')
    # ### end Alembic commands ###
