"""empty message

Revision ID: 65bcb7b899e2
Revises: 12778e0d070e
Create Date: 2020-06-04 22:16:05.073803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65bcb7b899e2'
down_revision = '12778e0d070e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'lead', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lead', type_='unique')
    # ### end Alembic commands ###
